[project]
name = "backend-vozfi"
version = "0.1.0"
description = "Es el backend de vozfi donde esta toda la integración de AI y servicios externos"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.139.0",
    "pydantic-settings>=2.7.0",
    "sqlalchemy>=2.0.36",
    "psycopg[binary]>=3.2.0",
    "alembic>=1.14.0",
    "uvicorn[standard]>=0.50.0",
    "huggingface-hub>=1.22.0",
    "python-multipart>=0.0.32",
    "langgraph>=1.2.7",
    "langchain-mcp-adapters>=0.3.0",
    "langchain-core>=1.4.8",
]
